[book]
title = "OntoDB Documentation"
authors = ["OntoDB Team"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://gitee.com/ontovalue/ontodb"
