[package]
name = "onto-server"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "OntoDB server"

[[bin]]
name = "ontodb-server"
path = "src/main.rs"

[dependencies]
onto-core = { workspace = true }
onto-storage = { workspace = true }
onto-ontology = { workspace = true }
onto-query = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
