apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ontodb
  namespace: ontodb
  labels:
    app.kubernetes.io/name: ontodb
    app.kubernetes.io/component: database
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ontodb
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
