apiVersion: v1
kind: Service
metadata:
  name: ontodb
  namespace: ontodb
  labels:
    app.kubernetes.io/name: ontodb
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - name: tcp
      port: 7913
      targetPort: tcp
      protocol: TCP
    - name: http
      port: 7912
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: ontodb
