# OntoDB One-Click Deployment Script (Windows PowerShell)
#
# Usage:
#   .\scripts\deploy.ps1 [OPTIONS]
#
# Options:
#   -Mode MODE        Deployment mode: docker | k8s | local (default: docker)
#   -Edition EDITION  Edition: oss | standard | gov (default: oss)
#   -Namespace NS     Kubernetes namespace (default: ontodb)
#   -Replicas N       Number of replicas for K8s (default: 3)
#   -SkipMonitoring   Skip monitoring stack setup
#   -SkipBackup       Skip backup configuration
#   -Help             Show this help

param(
    [ValidateSet("docker", "k8s", "local")]
    [string]$Mode = "docker",

    [ValidateSet("oss", "standard", "gov")]
    [string]$Edition = "oss",

    [string]$Namespace = "ontodb",

    [int]$Replicas = 3,

    [switch]$SkipMonitoring,

    [switch]$SkipBackup,

    [switch]$Help
)

# Colors
$Green = "`e[32m"
$Yellow = "`e[33m"
$Blue = "`e[34m"
$Red = "`e[31m"
$NC = "`e[0m"

# Show help
if ($Help) {
    Write-Host @"
OntoDB One-Click Deployment Script

Usage:
  .\scripts\deploy.ps1 [OPTIONS]

Options:
  -Mode MODE        Deployment mode: docker | k8s | local (default: docker)
  -Edition EDITION  Edition: oss | standard | gov (default: oss)
  -Namespace NS     Kubernetes namespace (default: ontodb)
  -Replicas N       Number of replicas for K8s (default: 3)
  -SkipMonitoring   Skip monitoring stack setup
  -SkipBackup       Skip backup configuration
  -Help             Show this help
"@
    exit 0
}

# Banner
Write-Host @"

  ____             _     ____  ____
 / ___| ___  _   _| | __|  _ \| __ )
| |  _ / _ \| | | | |/ / | | | |  _ \
| |_| | (_) | |_| |   <| |_| | |_) |
 \____|\___/ \__,_|_|\_\____/|____/

"@ -ForegroundColor Cyan

Write-Host "OntoDB Deployment Script" -ForegroundColor Green
Write-Host "Mode: $Mode | Edition: $Edition" -ForegroundColor Yellow
Write-Host ""

# Script directory
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectDir = Split-Path -Parent $ScriptDir

# Check prerequisites
function Check-Prerequisites {
    Write-Host "Checking prerequisites..." -ForegroundColor Blue

    switch ($Mode) {
        "docker" {
            if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
                Write-Host "Docker is not installed" -ForegroundColor Red
                exit 1
            }
            if (-not (Get-Command docker-compose -ErrorAction SilentlyContinue) -and -not (docker compose version 2>$null)) {
                Write-Host "Docker Compose is not installed" -ForegroundColor Red
                exit 1
            }
            Write-Host "✓ Docker and Docker Compose found" -ForegroundColor Green
        }
        "k8s" {
            if (-not (Get-Command kubectl -ErrorAction SilentlyContinue)) {
                Write-Host "kubectl is not installed" -ForegroundColor Red
                exit 1
            }
            Write-Host "✓ kubectl found" -ForegroundColor Green
        }
        "local" {
            if (-not (Get-Command cargo -ErrorAction SilentlyContinue)) {
                Write-Host "Rust/Cargo is not installed" -ForegroundColor Red
                exit 1
            }
            Write-Host "✓ Rust toolchain found" -ForegroundColor Green
        }
    }
}

# Generate configuration
function Generate-Config {
    Write-Host "Generating configuration..." -ForegroundColor Blue

    # Create config directory
    New-Item -ItemType Directory -Force -Path "$ProjectDir\config" | Out-Null

    # Generate API keys if not exists
    if (-not (Test-Path "$ProjectDir\config\api_keys.json")) {
        $randomKey1 = -join ((1..32) | ForEach-Object { '{0:x}' -f (Get-Random -Max 16) })
        $randomKey2 = -join ((1..32) | ForEach-Object { '{0:x}' -f (Get-Random -Max 16) })

        @"
{
  "enabled": true,
  "keys": [
    {
      "key": "ontodb-admin-$randomKey1",
      "description": "Admin key (generated by deploy script)",
      "permission": "Admin"
    },
    {
      "key": "ontodb-app-$randomKey2",
      "description": "Application key (generated by deploy script)",
      "permission": "ReadWrite"
    }
  ],
  "default_permission": "ReadOnly"
}
"@ | Out-File -FilePath "$ProjectDir\config\api_keys.json" -Encoding UTF8

        Write-Host "✓ Generated API keys" -ForegroundColor Green
    } else {
        Write-Host "! API keys already exist, skipping" -ForegroundColor Yellow
    }

    # Generate .env if not exists
    if (-not (Test-Path "$ProjectDir\.env")) {
        @"
# OntoDB Configuration
# Generated by deploy script

# Ports
ONTODB_HTTP_PORT=7912
ONTODB_TCP_PORT=7913
ONTODB_PG_PORT=5432

# Resources
ONTODB_MEMORY_LIMIT=2g
ONTODB_CPU_LIMIT=2.0
ONTODB_RATE_LIMIT=300
ONTODB_BURST_SIZE=50

# Backup
BACKUP_RETENTION_DAYS=7

# Monitoring
GRAFANA_PORT=3000
GRAFANA_ADMIN_PASSWORD=admin

# Edition-specific
ONTODB_EDITION=$Edition
"@ | Out-File -FilePath "$ProjectDir\.env" -Encoding UTF8

        Write-Host "✓ Generated .env file" -ForegroundColor Green
    } else {
        Write-Host "! .env already exists, skipping" -ForegroundColor Yellow
    }
}

# Build Docker image
function Build-DockerImage {
    Write-Host "Building Docker image..." -ForegroundColor Blue

    $buildArgs = ""
    switch ($Edition) {
        "oss" { $buildArgs = "--build-arg FEATURES=" }
        "standard" { $buildArgs = "--build-arg FEATURES=--features enterprise-standard" }
        "gov" { $buildArgs = "--build-arg FEATURES=--features enterprise-gov" }
    }

    Push-Location $ProjectDir
    docker build $buildArgs -t "ontodb:$Edition" .
    Pop-Location

    Write-Host "✓ Docker image built: ontodb:$Edition" -ForegroundColor Green
}

# Deploy with Docker Compose
function Deploy-Docker {
    Write-Host "Deploying with Docker Compose..." -ForegroundColor Blue

    Push-Location $ProjectDir

    if ($SkipMonitoring) {
        docker compose up -d ontodb
    } else {
        docker compose up -d
    }

    Pop-Location

    Write-Host "✓ Services started" -ForegroundColor Green

    # Wait for health check
    Write-Host "Waiting for OntoDB to be healthy..." -ForegroundColor Blue
    for ($i = 0; $i -lt 30; $i++) {
        try {
            $response = Invoke-WebRequest -Uri "http://localhost:7912/api/health/live" -UseBasicParsing -TimeoutSec 2
            if ($response.StatusCode -eq 200) {
                Write-Host "✓ OntoDB is healthy" -ForegroundColor Green
                return
            }
        } catch {}
        Start-Sleep -Seconds 2
    }

    Write-Host "! Health check timeout, please check manually" -ForegroundColor Yellow
}

# Deploy to Kubernetes
function Deploy-K8s {
    Write-Host "Deploying to Kubernetes..." -ForegroundColor Blue

    Push-Location $ProjectDir

    # Create namespace
    kubectl apply -f deploy/k8s/namespace.yaml

    # Create ConfigMap
    kubectl apply -f deploy/k8s/configmap.yaml -n $Namespace

    # Create PVC
    kubectl apply -f deploy/k8s/pvc.yaml -n $Namespace

    # Update and apply deployment
    $deployment = Get-Content deploy/k8s/deployment.yaml -Raw
    $deployment = $deployment -replace "replicas: 1", "replicas: $Replicas"
    $deployment = $deployment -replace "image: ontodb", "image: ontodb:$Edition"
    $deployment | kubectl apply -f - -n $Namespace

    # Create Service
    kubectl apply -f deploy/k8s/service.yaml -n $Namespace

    # Enable monitoring if not skipped
    if (-not $SkipMonitoring) {
        kubectl apply -f deploy/k8s/servicemonitor.yaml -n $Namespace 2>$null
        kubectl apply -f deploy/k8s/hpa.yaml -n $Namespace 2>$null
    }

    Pop-Location

    Write-Host "✓ Kubernetes deployment complete" -ForegroundColor Green

    # Wait for pods
    Write-Host "Waiting for pods to be ready..." -ForegroundColor Blue
    kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=ontodb -n $Namespace --timeout=120s
    Write-Host "✓ All pods ready" -ForegroundColor Green
}

# Deploy locally
function Deploy-Local {
    Write-Host "Building and running locally..." -ForegroundColor Blue

    Push-Location $ProjectDir

    # Build based on edition
    switch ($Edition) {
        "oss" { cargo build --release --bin ontodb-server }
        "standard" { cargo build --release --bin ontodb-server --features enterprise-standard }
        "gov" { cargo build --release --bin ontodb-server --features enterprise-gov }
    }

    Write-Host "✓ Build complete" -ForegroundColor Green

    # Create data directory
    New-Item -ItemType Directory -Force -Path ".\data\ontodb" | Out-Null

    # Start server
    Write-Host "Starting OntoDB server..." -ForegroundColor Blue
    $serverProcess = Start-Process -FilePath ".\target\release\ontodb-server.exe" `
        -ArgumentList "--data-dir", ".\data\ontodb", "--http", "0.0.0.0:7912", "--listen", "0.0.0.0:7913", "--auth", "--api-keys-file", ".\config\api_keys.json" `
        -PassThru -NoNewWindow

    Start-Sleep -Seconds 2

    if (-not $serverProcess.HasExited) {
        Write-Host "✓ OntoDB server started (PID: $($serverProcess.Id))" -ForegroundColor Green
    } else {
        Write-Host "✗ Failed to start OntoDB server" -ForegroundColor Red
        exit 1
    }

    Pop-Location
}

# Print access information
function Print-AccessInfo {
    Write-Host ""
    Write-Host "═══════════════════════════════════════════════════" -ForegroundColor Green
    Write-Host "          OntoDB Deployment Complete!" -ForegroundColor Green
    Write-Host "═══════════════════════════════════════════════════" -ForegroundColor Green
    Write-Host ""
    Write-Host "Access Information:" -ForegroundColor Blue
    Write-Host "  HTTP API:      http://localhost:7912" -ForegroundColor Yellow
    Write-Host "  TCP CLI:       localhost:7913" -ForegroundColor Yellow
    Write-Host "  PG Protocol:   localhost:5432" -ForegroundColor Yellow
    Write-Host "  Health Check:  http://localhost:7912/api/health" -ForegroundColor Yellow
    Write-Host "  Metrics:       http://localhost:7912/metrics" -ForegroundColor Yellow

    if (-not $SkipMonitoring) {
        Write-Host ""
        Write-Host "Monitoring:" -ForegroundColor Blue
        Write-Host "  Grafana:       http://localhost:3000 (admin/admin)" -ForegroundColor Yellow
        Write-Host "  Prometheus:    http://localhost:9090" -ForegroundColor Yellow
    }

    Write-Host ""
    Write-Host "API Keys:" -ForegroundColor Blue
    if (Test-Path "$ProjectDir\config\api_keys.json") {
        $keys = Get-Content "$ProjectDir\config\api_keys.json" | ConvertFrom-Json
        $adminKey = $keys.keys[0].key
        Write-Host "  Admin Key:     $adminKey" -ForegroundColor Yellow
    }

    Write-Host ""
    Write-Host "Edition: $Edition" -ForegroundColor Blue
    Write-Host ""
    Write-Host "Quick Test:" -ForegroundColor Blue
    Write-Host "  curl http://localhost:7912/api/health" -ForegroundColor Yellow
    Write-Host ""
}

# Main execution
Check-Prerequisites
Generate-Config

switch ($Mode) {
    "docker" {
        Build-DockerImage
        Deploy-Docker
    }
    "k8s" {
        Build-DockerImage
        Deploy-K8s
    }
    "local" {
        Deploy-Local
    }
}

Print-AccessInfo
