#!/bin/bash
# OntoDB One-Click Deployment Script
#
# Usage:
#   ./scripts/deploy.sh [OPTIONS]
#
# Options:
#   --mode MODE        Deployment mode: docker | k8s | local (default: docker)
#   --edition EDITION  Edition: oss | standard | gov (default: oss)
#   --namespace NS     Kubernetes namespace (default: ontodb)
#   --replicas N       Number of replicas for K8s (default: 3)
#   --skip-monitoring  Skip monitoring stack setup
#   --skip-backup      Skip backup configuration
#   --help             Show this help

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default values
MODE="docker"
EDITION="oss"
NAMESPACE="ontodb"
REPLICAS=3
SKIP_MONITORING=false
SKIP_BACKUP=false
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --mode)
            MODE="$2"
            shift 2
            ;;
        --edition)
            EDITION="$2"
            shift 2
            ;;
        --namespace)
            NAMESPACE="$2"
            shift 2
            ;;
        --replicas)
            REPLICAS="$2"
            shift 2
            ;;
        --skip-monitoring)
            SKIP_MONITORING=true
            shift
            ;;
        --skip-backup)
            SKIP_BACKUP=true
            shift
            ;;
        --help)
            head -20 "$0" | tail -18
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            exit 1
            ;;
    esac
done

# Print banner
echo -e "${BLUE}"
echo "  ____             _     ____  ____  "
echo " / ___| ___  _   _| | __|  _ \| __ ) "
echo "| |  _ / _ \| | | | |/ / | | | |  _ \ "
echo "| |_| | (_) | |_| |   <| |_| | |_) |"
echo " \____|\___/ \__,_|_|\_\____/|____/ "
echo -e "${NC}"
echo -e "${GREEN}OntoDB Deployment Script${NC}"
echo -e "Mode: ${YELLOW}${MODE}${NC} | Edition: ${YELLOW}${EDITION}${NC}"
echo ""

# Validate edition
case $EDITION in
    oss|standard|gov)
        ;;
    *)
        echo -e "${RED}Invalid edition: ${EDITION}. Use: oss, standard, gov${NC}"
        exit 1
        ;;
esac

# Function to check prerequisites
check_prerequisites() {
    echo -e "${BLUE}Checking prerequisites...${NC}"

    case $MODE in
        docker)
            if ! command -v docker &> /dev/null; then
                echo -e "${RED}Docker is not installed${NC}"
                exit 1
            fi
            if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
                echo -e "${RED}Docker Compose is not installed${NC}"
                exit 1
            fi
            echo -e "${GREEN}✓ Docker and Docker Compose found${NC}"
            ;;
        k8s)
            if ! command -v kubectl &> /dev/null; then
                echo -e "${RED}kubectl is not installed${NC}"
                exit 1
            fi
            if ! kubectl cluster-info &> /dev/null; then
                echo -e "${RED}Cannot connect to Kubernetes cluster${NC}"
                exit 1
            fi
            echo -e "${GREEN}✓ kubectl configured and cluster accessible${NC}"
            ;;
        local)
            if ! command -v cargo &> /dev/null; then
                echo -e "${RED}Rust/Cargo is not installed${NC}"
                exit 1
            fi
            echo -e "${GREEN}✓ Rust toolchain found${NC}"
            ;;
    esac
}

# Function to generate configuration
generate_config() {
    echo -e "${BLUE}Generating configuration...${NC}"

    # Create config directory if not exists
    mkdir -p "$PROJECT_DIR/config"

    # Generate API keys if not exists
    if [ ! -f "$PROJECT_DIR/config/api_keys.json" ]; then
        cat > "$PROJECT_DIR/config/api_keys.json" <<EOF
{
  "enabled": true,
  "keys": [
    {
      "key": "ontodb-admin-$(openssl rand -hex 16)",
      "description": "Admin key (generated by deploy script)",
      "permission": "Admin"
    },
    {
      "key": "ontodb-app-$(openssl rand -hex 16)",
      "description": "Application key (generated by deploy script)",
      "permission": "ReadWrite"
    }
  ],
  "default_permission": "ReadOnly"
}
EOF
        echo -e "${GREEN}✓ Generated API keys${NC}"
    else
        echo -e "${YELLOW}! API keys already exist, skipping${NC}"
    fi

    # Generate .env if not exists
    if [ ! -f "$PROJECT_DIR/.env" ]; then
        cat > "$PROJECT_DIR/.env" <<EOF
# OntoDB Configuration
# Generated by deploy script

# Ports
ONTODB_HTTP_PORT=7912
ONTODB_TCP_PORT=7913
ONTODB_PG_PORT=5432

# Resources
ONTODB_MEMORY_LIMIT=2g
ONTODB_CPU_LIMIT=2.0
ONTODB_RATE_LIMIT=300
ONTODB_BURST_SIZE=50

# Backup
BACKUP_RETENTION_DAYS=7

# Monitoring
GRAFANA_PORT=3000
GRAFANA_ADMIN_PASSWORD=admin

# Edition-specific
ONTODB_EDITION=${EDITION}
EOF
        echo -e "${GREEN}✓ Generated .env file${NC}"
    else
        echo -e "${YELLOW}! .env already exists, skipping${NC}"
    fi
}

# Function to build Docker image
build_docker_image() {
    echo -e "${BLUE}Building Docker image...${NC}"

    local build_args=""
    case $EDITION in
        oss)
            build_args="--build-arg FEATURES="
            ;;
        standard)
            build_args="--build-arg FEATURES=--features enterprise-standard"
            ;;
        gov)
            build_args="--build-arg FEATURES=--features enterprise-gov"
            ;;
    esac

    cd "$PROJECT_DIR"
    docker build $build_args -t ontodb:${EDITION} .
    echo -e "${GREEN}✓ Docker image built: ontodb:${EDITION}${NC}"
}

# Function to deploy with Docker Compose
deploy_docker() {
    echo -e "${BLUE}Deploying with Docker Compose...${NC}"

    cd "$PROJECT_DIR"

    # Update docker-compose.yml with edition
    export ONTODB_EDITION=$EDITION

    # Start services
    if [ "$SKIP_MONITORING" = true ]; then
        docker compose up -d ontodb
    else
        docker compose up -d
    fi

    echo -e "${GREEN}✓ Services started${NC}"

    # Wait for health check
    echo -e "${BLUE}Waiting for OntoDB to be healthy...${NC}"
    for i in {1..30}; do
        if curl -s http://localhost:7912/api/health/live > /dev/null 2>&1; then
            echo -e "${GREEN}✓ OntoDB is healthy${NC}"
            return 0
        fi
        sleep 2
    done

    echo -e "${YELLOW}! Health check timeout, please check manually${NC}"
}

# Function to deploy to Kubernetes
deploy_k8s() {
    echo -e "${BLUE}Deploying to Kubernetes...${NC}"

    cd "$PROJECT_DIR"

    # Create namespace
    kubectl apply -f deploy/k8s/namespace.yaml

    # Create ConfigMap
    kubectl apply -f deploy/k8s/configmap.yaml -n $NAMESPACE

    # Create PVC
    kubectl apply -f deploy/k8s/pvc.yaml -n $NAMESPACE

    # Update deployment with edition and replicas
    sed "s/replicas: 1/replicas: $REPLICAS/g" deploy/k8s/deployment.yaml | \
        sed "s|image: ontodb|image: ontodb:${EDITION}|g" | \
        kubectl apply -f - -n $NAMESPACE

    # Create Service
    kubectl apply -f deploy/k8s/service.yaml -n $NAMESPACE

    # Enable monitoring if not skipped
    if [ "$SKIP_MONITORING" = false ]; then
        kubectl apply -f deploy/k8s/servicemonitor.yaml -n $NAMESPACE 2>/dev/null || true
        kubectl apply -f deploy/k8s/hpa.yaml -n $NAMESPACE 2>/dev/null || true
    fi

    echo -e "${GREEN}✓ Kubernetes deployment complete${NC}"

    # Wait for pods
    echo -e "${BLUE}Waiting for pods to be ready...${NC}"
    kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=ontodb -n $NAMESPACE --timeout=120s
    echo -e "${GREEN}✓ All pods ready${NC}"
}

# Function to deploy locally
deploy_local() {
    echo -e "${BLUE}Building and running locally...${NC}"

    cd "$PROJECT_DIR"

    # Build based on edition
    case $EDITION in
        oss)
            cargo build --release --bin ontodb-server
            ;;
        standard)
            cargo build --release --bin ontodb-server --features enterprise-standard
            ;;
        gov)
            cargo build --release --bin ontodb-server --features enterprise-gov
            ;;
    esac

    echo -e "${GREEN}✓ Build complete${NC}"

    # Create data directory
    mkdir -p ./data/ontodb

    # Start server
    echo -e "${BLUE}Starting OntoDB server...${NC}"
    ./target/release/ontodb-server \
        --data-dir ./data/ontodb \
        --http 0.0.0.0:7912 \
        --listen 0.0.0.0:7913 \
        --auth \
        --api-keys-file ./config/api_keys.json &
    SERVER_PID=$!

    # Wait for startup
    sleep 2

    if kill -0 $SERVER_PID 2>/dev/null; then
        echo -e "${GREEN}✓ OntoDB server started (PID: $SERVER_PID)${NC}"
    else
        echo -e "${RED}✗ Failed to start OntoDB server${NC}"
        exit 1
    fi
}

# Function to print access information
print_access_info() {
    echo ""
    echo -e "${GREEN}═══════════════════════════════════════════════════${NC}"
    echo -e "${GREEN}          OntoDB Deployment Complete!${NC}"
    echo -e "${GREEN}═══════════════════════════════════════════════════${NC}"
    echo ""
    echo -e "${BLUE}Access Information:${NC}"
    echo -e "  HTTP API:      ${YELLOW}http://localhost:7912${NC}"
    echo -e "  TCP CLI:       ${YELLOW}localhost:7913${NC}"
    echo -e "  PG Protocol:   ${YELLOW}localhost:5432${NC}"
    echo -e "  Health Check:  ${YELLOW}http://localhost:7912/api/health${NC}"
    echo -e "  Metrics:       ${YELLOW}http://localhost:7912/metrics${NC}"

    if [ "$SKIP_MONITORING" = false ]; then
        echo ""
        echo -e "${BLUE}Monitoring:${NC}"
        echo -e "  Grafana:       ${YELLOW}http://localhost:3000${NC} (admin/admin)"
        echo -e "  Prometheus:    ${YELLOW}http://localhost:9090${NC}"
    fi

    echo ""
    echo -e "${BLUE}API Keys:${NC}"
    if [ -f "$PROJECT_DIR/config/api_keys.json" ]; then
        ADMIN_KEY=$(grep -o '"key": "[^"]*"' "$PROJECT_DIR/config/api_keys.json" | head -1 | cut -d'"' -f4)
        echo -e "  Admin Key:     ${YELLOW}${ADMIN_KEY}${NC}"
    fi

    echo ""
    echo -e "${BLUE}Edition:${NC} ${YELLOW}${EDITION}${NC}"
    echo ""
    echo -e "${BLUE}Quick Test:${NC}"
    echo -e "  curl http://localhost:7912/api/health"
    echo ""
}

# Main execution
check_prerequisites
generate_config

case $MODE in
    docker)
        build_docker_image
        deploy_docker
        ;;
    k8s)
        build_docker_image
        deploy_k8s
        ;;
    local)
        deploy_local
        ;;
esac

print_access_info
